import { Router } from "express";
import * as controller from "../controllers/attendance.controller";
import { authenticate } from "../middlewares/auth.middleware";
import { requirePermission } from "../middlewares/role.middleware";
export const attendanceRoutes = Router();
attendanceRoutes.use(authenticate);
attendanceRoutes.get("/", requirePermission("Attendance", "canView"), controller.list);
attendanceRoutes.put("/", requirePermission("Attendance", "canUpdate"), controller.upsert);
attendanceRoutes.post("/check-in", requirePermission("Employee Portal", "canCreate"), controller.checkIn);
attendanceRoutes.post("/check-out", requirePermission("Employee Portal", "canCreate"), controller.checkOut);
attendanceRoutes.get("/employee/:id", requirePermission("Attendance", "canView"), controller.employeeHistory);
