export const apiDocumentation = {
  tags: ["Auth", "Attendance", "Leaves", "Employees", "Tasks", "Products", "Inventory", "Vendors", "Customers", "Invoices"].map((name) => ({ name })),
  components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } } },
  security: [{ bearerAuth: [] }],
  paths: {
    "/auth/login": { post: { tags: ["Auth"], summary: "Log in with email and password", security: [], responses: { "200": { description: "JWT tokens and user payload" } } } },
    "/auth/me": { get: { tags: ["Auth"], summary: "Get current authenticated user", responses: { "200": { description: "Current user" } } } },
    "/attendance": {
      get: { tags: ["Attendance"], summary: "List attendance records", responses: { "200": { description: "Attendance records" } } },
      put: { tags: ["Attendance"], summary: "Create or update an attendance entry for a specific employee and date", responses: { "200": { description: "Attendance record" } } },
    },
    "/attendance/check-in": { post: { tags: ["Attendance"], summary: "Check in the current employee", responses: { "201": { description: "Attendance record" } } } },
    "/attendance/check-out": { post: { tags: ["Attendance"], summary: "Check out the current employee", responses: { "200": { description: "Attendance record" } } } },
    "/attendance/employee/{id}": { get: { tags: ["Attendance"], summary: "List attendance for one employee", responses: { "200": { description: "Employee attendance history" } } } },
    "/leaves": { get: { tags: ["Leaves"], summary: "List leave requests", responses: { "200": { description: "Leave requests" } } } },
    "/leaves/request": { post: { tags: ["Leaves"], summary: "Request leave", responses: { "201": { description: "Leave request" } } } },
    "/leaves/{id}/approve": { put: { tags: ["Leaves"], summary: "Approve leave", responses: { "200": { description: "Approved leave" } } } },
    "/leaves/{id}/reject": { put: { tags: ["Leaves"], summary: "Reject leave", responses: { "200": { description: "Rejected leave" } } } },
    "/leaves/employee/{id}": { get: { tags: ["Leaves"], summary: "List leave history for one employee", responses: { "200": { description: "Employee leave history" } } } },
    "/employees": { get: { tags: ["Employees"], summary: "List employees", responses: { "200": { description: "Employees" } } }, post: { tags: ["Employees"], summary: "Create employee", responses: { "201": { description: "Employee" } } } },
    "/employees/{id}": { patch: { tags: ["Employees"], summary: "Update employee", responses: { "200": { description: "Updated employee" } } }, delete: { tags: ["Employees"], summary: "Disable employee", responses: { "200": { description: "Disabled employee" } } } },
    "/employees/{id}/profile": { get: { tags: ["Employees"], summary: "Get employee profile", responses: { "200": { description: "Employee profile" } } } },
    "/tasks": { get: { tags: ["Tasks"], summary: "List tasks", responses: { "200": { description: "Tasks" } } }, post: { tags: ["Tasks"], summary: "Create task", responses: { "201": { description: "Task" } } } },
    "/tasks/{id}": { patch: { tags: ["Tasks"], summary: "Update task", responses: { "200": { description: "Updated task" } } } },
    "/tasks/{id}/assign": { post: { tags: ["Tasks"], summary: "Assign task", responses: { "200": { description: "Updated task" } } } },
    "/tasks/{id}/history": { get: { tags: ["Tasks"], summary: "Get task audit history", responses: { "200": { description: "Task history" } } } },
    "/products": { get: { tags: ["Products"], summary: "List products", responses: { "200": { description: "Products" } } }, post: { tags: ["Products"], summary: "Create product", responses: { "201": { description: "Product" } } } },
    "/products/{id}": { put: { tags: ["Products"], summary: "Update product", responses: { "200": { description: "Updated product" } } }, delete: { tags: ["Products"], summary: "Delete product", responses: { "204": { description: "Deleted" } } } },
    "/inventory": { get: { tags: ["Inventory"], summary: "List current stock", responses: { "200": { description: "Inventory" } } } },
    "/inventory/stock-in": { post: { tags: ["Inventory"], summary: "Add stock", responses: { "200": { description: "Updated inventory" } } } },
    "/inventory/stock-out": { post: { tags: ["Inventory"], summary: "Remove stock", responses: { "200": { description: "Updated inventory" } } } },
    "/inventory/low-stock": { get: { tags: ["Inventory"], summary: "List low stock items", responses: { "200": { description: "Low stock inventory" } } } },
    "/vendors": { get: { tags: ["Vendors"], summary: "List vendors", responses: { "200": { description: "Vendors" } } }, post: { tags: ["Vendors"], summary: "Create vendor", responses: { "201": { description: "Vendor" } } } },
    "/vendors/{id}": { put: { tags: ["Vendors"], summary: "Update vendor", responses: { "200": { description: "Updated vendor" } } }, delete: { tags: ["Vendors"], summary: "Delete vendor", responses: { "204": { description: "Deleted" } } } },
    "/customers": { get: { tags: ["Customers"], summary: "List customers", responses: { "200": { description: "Customers" } } }, post: { tags: ["Customers"], summary: "Create customer", responses: { "201": { description: "Customer" } } } },
    "/customers/{id}": { put: { tags: ["Customers"], summary: "Update customer", responses: { "200": { description: "Updated customer" } } }, delete: { tags: ["Customers"], summary: "Delete customer", responses: { "204": { description: "Deleted" } } } },
    "/invoices": { get: { tags: ["Invoices"], summary: "List invoices", responses: { "200": { description: "Invoices" } } }, post: { tags: ["Invoices"], summary: "Create invoice and deduct stock", responses: { "201": { description: "Invoice" } } } },
    "/invoices/{id}": { get: { tags: ["Invoices"], summary: "Get invoice", responses: { "200": { description: "Invoice" } } } },
    "/invoices/{id}/pdf": { get: { tags: ["Invoices"], summary: "Download invoice PDF", responses: { "200": { description: "PDF invoice" } } } },
  },
};
